### ISSUE TITLE
Cannot create PR from main to prod in repo

### ISSUE THREAD

**Issue by danielegobbetti** [noi-techpark/sfscon-maps#16]
@clezag asked me to create a PR when production (branch prod) should be aligned to testing (branch main).

I just tried to do so but it is not possible for outside users, as per error:
![image](https://github.com/user-attachments/assets/fc9bf2c8-b52a-4431-9faa-72edbbff21ad)

@sseppi or @clezag I'll let you handle this internally, I can confirm the the current testing environment works as intended and contains the latest changes by the sfscon team.

**Comment by clezag** [comment]
@danielegobbetti I've added you as a collaborator with 'triage' role, can you retry creating the PR?
I'd like you (and the sfscon team) to be as autonomous with this as possible

**Comment by danielegobbetti** [comment]
looks like it worked. Thanks!
