### ISSUE TITLE
As an SFSCON participant I want to have a navigation system online, to find the room I'm looking for

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/sfscon-maps#2]
URL: https://maps.sfscon.testingmachine.eu/@floor0,346.86,207.6,1.48

**Comment by rcavaliere** [comment]
@clezag prepared the CI/CD, repository, etc. in our github infrastructure -> https://github.com/noi-techpark/sfscon-maps
Development in progress by D.Gobbetti.

**Comment by sseppi** [comment]
@clezag After talking with the SFSCON team, I think we are ready to put the first version intro production on maps.sfscon.it
