### ISSUE TITLE
How to handle the header logo

### ISSUE THREAD

**Issue by danielegobbetti** [noi-techpark/sfscon-maps#4]
Hello,

in order set the header logo properly, some changes have to be performed. I see two possible approaches:

Approach 1:
Map an additional path in the container as is done [in the upstream repo](https://github.com/c3nav/c3nav/blob/09b2375d79707446ee7a618646dcde5fe53fe749/docker/entrypoint.sh#L36) and put the logo svg file there, then refer to this position in the configuration file.

Approach 2:
Define a subdirectory of the ``data`` directory (e.g. ``data/logo/``) and upload the file there, then refer to this position in the configuration file.

For approach 1, a change to the docker configuration is needed, for approach 2, a change to the ``.gitignore`` settings must be performed, and before proceeding with either approaches I wanted to discuss which is best according to @clezag (and any other maintainers).
I tested both approaches locally and they both are feasible from the point of view of c3nav.

**Comment by sseppi** [comment]
@danielegobbetti the logo file must be in the project directory or could it be also an external resource?

If can be also an external resource we could follow the strategy we use also for other application that foresees the following steps:

1. upload the logo in a SFSCON folder on the "Third Party Assets" repository: https://github.com/noi-techpark/third-party-assets/tree/main/assets
2. the logo will be published at the following link: https://third-party.opendatahub.com/ 
3. use this link to get the right logo to be shown.

**Comment by clezag** [comment]
I'd be fine with either solution, but I'm tending more towards number 1, as the data directory already contains deployment specific configuration stuff that one has to mount.

Feel free to modify the .gitignore to exclude the logo itself, analogous to the config file; ignoring the /data directory was done mainly to avoid accidental commits after testing locally.

**Comment by danielegobbetti** [comment]
Alright lets go with option 1.

@sseppi on my instance I took the logo svg from the main sfscon site ( https://www.sfscon.it/wp-content/themes/sfscon/images/logo.svg ) but this file lacks the license information and the pre-commit hook is correctly preventing its addition to the repo.

I kindly ask you to either:
- provide me the correct licensing to attach to the aforementioned file
- give me another resource with the correct licensing information attached
- add the appropriate logo to this repository in the ``data/logo`` subfolder (as this path has been tested by me and does not create conflicts with the app functionalities)

**Comment by sseppi** [comment]
@danielegobbetti I asked the SFSCON organization team, they told me that the license of the SFSCON logo is cc0.

**Comment by danielegobbetti** [comment]
@sseppi please review the copyright as I copied the one of the configuration file since you did not specify otherwise: https://github.com/noi-techpark/sfscon-maps/blob/64df2faa91ea3395bcd090a0ad67888302f050ec/data/logo/sfscon.svg#L2

Maintainers can edit the PR hence you can perform the fixes autonomously before merging.
