### ISSUE TITLE
As an SFSCON maps maintainer I want to bring the application into production, creating the necessary CI/CD pipeline

### ISSUE THREAD

**Issue by clezag** [noi-techpark/sfscon-maps#9]
@clezag After talking with the SFSCON team, I think we are ready to put the first version intro production on maps.sfscon.it

_Originally posted by @sseppi in https://github.com/noi-techpark/sfscon-maps/issues/2#issuecomment-2367396753_
            
- [x] Setup CI/CD
- [x] Figure out DB upgrade path (#5 )
- [ ] Move to RDS instance for production

**Comment by clezag** [comment]
@danielegobbetti I've set up production along testing, but in the process I think it nuked the testing DB (testing and prod pointed to the same volume by mistake).
Do you have a dump we can load, or better yet to use to set up the migration pipeline?
When we have figured out the upgrade process, we can move to an actual RDS instance with backups etc.

**Comment by danielegobbetti** [comment]
> @danielegobbetti I've set up production along testing, but in the process I think it nuked the testing DB (testing and prod pointed to the same volume by mistake). Do you have a dump we can load, or better yet to use to set up the migration pipeline? When we have figured out the upgrade process, we can move to an actual RDS instance with backups etc.

On the testing vm there are a couple of dumps ready to be restored. I left the whole history of what I imported there, but consider taking the most recent one.

I'm out of office for the rest of the day, hence I'll not be able to follow up much. The actual import command is adapted from the main repo, but you find it in the history of my user as well.

**Comment by clezag** [comment]
I've managed to load your dump for test and production, so that's nice.
But it didn't run out of the box, and threw a load of http 500 errors due to some cached images not found.
I think this is because the data directory is not preserved across deployments.

In the end this command fixed it for me, should we call this at launch, too?
```bash
docker exec -it -w /app c3nav-prod-c3nav-core-1 /app/env/bin/python manage.py clearmapcache --include-history --include-geometries
```


Note, that I had to rename the compose deployment, so you will have to swap out `c3nav` with `c3nav-test` and `c3nav-prod` accordingly in your scripts

**Comment by danielegobbetti** [comment]
> In the end this command fixed it for me, should we call this at launch, too?
> 
> ```shell
> docker exec -it -w /app c3nav-prod-c3nav-core-1 /app/env/bin/python manage.py clearmapcache --include-history --include-geometries
> ```

Yes add this to the scripts called at launch, I was testing the right incantation but if you found one that works I'd go for this.
 
> Note, that I had to rename the compose deployment, so you will have to swap out `c3nav` with `c3nav-test` and `c3nav-prod` accordingly in your scripts

Noted, thanks!

**Comment by clezag** [comment]
Closing this, since we're solidly in production, and moving to RDS is not necessary as it stands now
